### ISSUE TITLE
Use an existing VG?

### ISSUE THREAD

**Issue by murkylife** [alibaba/open-local#104]
## Question
Is it possible to use an existing VG with this project? I already have a PV and VG created, and the VG has 100GB free to create LVs. 

Would it be possible to configure open-local to create new LVs in the existing VG? If it's possible, would appreciate any help.

**Comment by TheBeatles1994** [comment]
Sure, you can edit nls resource to use your existing VG.

kubectl edit nls [node name]

```yaml
apiVersion: csi.aliyun.com/v1alpha1
kind: NodeLocalStorage
spec:
  nodeName: [node name]
  listConfig:
    vgs: 
      include:
      - [your VG name]
      - open-local-pool-[0-9]+
```

when your existing VG name appears in the status.nodeStorageInfo.volumeGroups of this nls, means you can use this VG to create your Persistent Volume.

**Comment by murkylife** [comment]
Thanks, ill give this a try!

Is it possible to configure this in the values.yaml? My cluster is defined declaratively and I prefer to keep the state in my repo.

**Comment by murkylife** [comment]
How about if i do it this way:
- add crds
- create nls
- install helm chart

Will it respect my nls settings? Or will it override.

**Comment by TheBeatles1994** [comment]
> Thanks, ill give this a try!
> 
> Is it possible to configure this in the values.yaml? My cluster is defined declaratively and I prefer to keep the state in my repo.

Sure! And contributions to this project are very welcome!

**Comment by TheBeatles1994** [comment]
> How about if i do it this way:
> 
> * add crds
> * create nls
> * install helm chart
> 
> Will it respect my nls settings? Or will it override.

No nls will be created or overrided if there is an existing nls.

**Comment by murkylife** [comment]
Thanks for your help. I was able to get it working after I added the crds from "csi.aliyun.com_nodelocalstorages.yaml", then defined the nls, and after that installed the helm chart.

However, init-jobs are permanently pending due to an affinity issue, as they're set to not run on master. My set up is a single node k3s cluster so I only have a master node.

It appears to be working fine without the init-job, and I've raised a PR to allow disabling them: https://github.com/alibaba/open-local/pull/105

**Comment by TheBeatles1994** [comment]
But you need init-job, it will modify kube-scheduler.yaml file of each master node to configure scheduler policy.

**Comment by murkylife** [comment]
The files its trying to modify dont exist there on k3s. Whats the scheduler policy needed for? I was able to create and delete pvc without it.

**Comment by TheBeatles1994** [comment]
Open-Local is a local disk management system, this means open-local must choose a node from cluster, and consider how many storage capacity in each node can use, and which volume group it will use to create volume and snapshot.

So k8s scheduler must contain storage scheduling algorithm of open-local, we extend filtering and scoring algorithms in extender way, you can see it in init-job file.

https://github.com/alibaba/open-local/blob/fec04e4b57b834c8f1180d1c70bf131544d85d97/helm/templates/init-job.yaml#L58-L60

**Comment by murkylife** [comment]
What about if you just have 1 node? Then is that still needed?

**Comment by TheBeatles1994** [comment]
> What about if you just have 1 node? Then is that still needed?

This has nothing to do with the number of nodes. You must configure this otherwise the k8s cluster will have no local storage scheduling capability.

> It appears to be working fine without the init-job

Because your k3s cluster only have a master node, and you specify the vg name in storage class, it work fine. But it will work abnormally if the cluster size exceeds one node.

**Comment by murkylife** [comment]
Thanks. How can i get it working on my single node cluster considering there is a nodetaint which specifies it can only run on non-master? It is stuck in pending.

Im happy to do a pr to address anything, but would appreciate your direction.

**Comment by TheBeatles1994** [comment]
I'm not familiar with k3s. Is your kube-scheduler static pod?

**Comment by murkylife** [comment]
"k3s bundles the Kubernetes components (kube-apiserver, kube-controller-manager, kube-scheduler, kubelet, kube-proxy) into combined processes that are presented as a simple server and agent model.": https://www.suse.com/c/rancher_blog/introducing-k3s-the-lightweight-kubernetes-distribution-built-for-the-edge/

**Comment by murkylife** [comment]
I've done more research and here's what I've found. 

1. The kube-scheduler "--policy-config-file" that you're using is deprecated and will be going away in kubernetes 1.23. You will need to migrate to "kube-scheduler --config" as documented here: https://kubernetes.io/docs/reference/scheduling/config/

2. While k3s doesn't have a pod for kube-scheduler, we have the option of [providing arguments to it](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#customized-flags). So assuming I create a scheduler.yaml in my server with the extenders that you're creating, I can do something like:
```
--kube-scheduler-arg config=/etc/rancher/k3s/scheduler.yaml
```

Will you consider removing the requirement of the init-job.yaml, and give us the option to configure kube-scheduler ourselves?

**Comment by TheBeatles1994** [comment]
> I've done more research and here's what I've found. 
> 
> 1. The kube-scheduler "--policy-config-file" that you're using is deprecated and will be going away in kubernetes 1.23. You will need to migrate to "kube-scheduler --config" as documented here: https://kubernetes.io/docs/reference/scheduling/config/
> 
> I haven't tested, but it could be like this:
> ```
> ---
> apiVersion: kubescheduler.config.k8s.io/v1beta3
> kind: KubeSchedulerConfiguration
> extenders:
> - urlPrefix: http://open-local-scheduler-extender.kube-system:23000/scheduler
>   filterVerb: predicates
>   prioritizeVerb: priorities
>   preemptVerb: ''
>   bindVerb: ''
>   weight: 10
>   enableHttps: false
>   nodeCacheCapable: true
>   ignorable: true
> profiles:
> - pluginConfig:
>   - name: InterPodAffinity 
>     args:
>       apiVersion: kubescheduler.config.k8s.io/v1beta3
>       kind: InterPodAffinityArgs
>       hardPodAffinityWeight: 10
> ```
> 
> 2. While k3s doesn't have a pod for kube-scheduler, we have the option of [providing arguments to it](https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#customized-flags). So assuming I create a scheduler.yaml in my server with the extenders [here](https://github.com/alibaba/open-local/blob/5a914343a7caf8b37949df51e4eab2dc1d9b6d9a/helm/templates/init-job.yaml#L57), I can do something like:
> ```
> --kube-scheduler-arg config=/etc/rancher/k3s/scheduler.yaml
> ```
> 
> Will you consider removing the requirement of the init-job.yaml, and give us the option to configure kube-scheduler ourselves? Perhaps you can have it default to running the init-job, and we can disable if we will configure the scheduler separately?
> 
> 

These days are Chinese new year, I may be slow to respond...

**Comment by TheBeatles1994** [comment]
These days are Chinese new year, I may be slow to respond...

**Comment by Seryta** [comment]
I also use k3s, and I added the k3s service startup parameter:

``` yaml
--kube-scheduler-arg config=/etc/rancher/k3s/scheduler.yaml

scheduler.yaml:
---
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
extenders:
- urlPrefix: http://open-local-scheduler-extender.open-local:23000/scheduler
  filterVerb: predicates
  prioritizeVerb: priorities
  preemptVerb: ''
  bindVerb: ''
  weight: 10
  enableHTTPS: false
  nodeCacheCapable: true
  ignorable: true
profiles:
- pluginConfig:
  - name: InterPodAffinity 
    args:
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: InterPodAffinityArgs
      hardPodAffinityWeight: 10
```

As a result, after I restart the k3s service, it has been rebooting circularly, and I didn't see the relevant error reports.

Have you run successfully?


@murkylife

**Comment by Seryta** [comment]
I modified the parameters and successfully run the k3s service. I am a single master and two node cluster. How to verify whether the scheduling policy is effective? @TheBeatles1994 

``` shell
        --kube-scheduler-arg policy-config-file=/etc/rancher/k3s/scheduler.json
```

scheduler.json:
``` yaml
{
"kind" : "Policy",
"apiVersion" : "v1",
"extenders" : [{
   "urlPrefix": "http://{{ .Values.extender.name }}.{{.Values.namespace}}:23000/scheduler",
   "filterVerb": "predicates",
   "prioritizeVerb": "priorities",
   "preemptVerb": "",
   "bindVerb": "",
   "weight": 10,
   "enableHttps": false,
   "nodeCacheCapable": true,
   "ignorable": true
   }],
   "hardPodAffinitySymmetricWeight" : 10
}
```
