### ISSUE TITLE
how to use open-local in certain nodes

### ISSUE THREAD

**Issue by FreshMan123** [alibaba/open-local#173]
## Question

the cluster have six nodes and each node has /dev/vdb available. however, only three of them can be used in open-local. how can I configure so the open-local only use these three nodes. Currently, the open-local will be install firstly so it recognizes all node are available. however, only three of them can be used in this case.

**Comment by TheBeatles1994** [comment]
you can edit nlsc to tell open-local how to initialize storage device in different nodes:

```yaml
apiVersion: csi.aliyun.com/v1alpha1
kind: NodeLocalStorageInitConfig
metadata:
  name: [ nlsc 名称 ]
spec:
  # globalConfig:     # global configuration, you can ignore it
  nodesConfig:  
  - selector: 
      matchExpressions:
      - key: [your node label key]
        operator: In
        values:
        - [your node label value]
    listConfig:
      vgs:
        include:
        - [vg name]
    resourceInit:
      vg:
      - vgName: [vg name]
        devices:
        - /dev/vdb
```
