### ISSUE TITLE
I need LVM to specify a SSD or HDD type disk

### ISSUE THREAD

**Issue by dxygit1** [alibaba/open-local#255]
Does the openlocal lvm type support specifying mediaType
I need LVM to specify a SSD or HDD type disk

for example
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvm-xfs-ssd
{{ include "local.labels" . | indent 2 }}
provisioner: {{ .Values.driver }}
parameters:
  volumeType: "LVM"
  csi.storage.k8s.io/fstype: xfs
  mediaType: ssd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
